version: '3.8'
services:
  frontend:
    image:  girlysheet.azurecr.io/aglorhythm/girlysheet-website:latest
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    restart: unless-stopped

 